import type { DatabaseSchema, Table } from "@/lib/schema/types";

function keyBadges(table: Table, columnName: string): string[] {
  const col = table.columns.find((c) => c.name === columnName);
  if (!col) return [];
  const badges: string[] = [];
  if (col.primaryKey) badges.push("🔑 PK");
  if (col.unique) badges.push("UQ");
  if (col.foreignKey) badges.push("FK");
  return badges;
}

/** Generate a self-contained Markdown reference document for the schema. */
export function generateMarkdownDocs(schema: DatabaseSchema, projectName: string): string {
  const date = new Date().toISOString().slice(0, 10);
  const out: string[] = [];

  out.push(`# ${projectName} — Schema documentation`);
  out.push("");
  out.push(
    `> Generated by SchemaFlow on ${date} · dialect: ${schema.dialect} · ${schema.tables.length} tables · ${schema.relationships.length} relationships`,
  );
  out.push("");

  if (schema.tables.length === 0) {
    out.push("_No tables in this schema._");
    return out.join("\n");
  }

  out.push("## Tables");
  out.push("");
  for (const table of schema.tables) {
    out.push(`### ${table.name}${table.schema ? ` _(${table.schema})_` : ""}`);
    out.push("");
    out.push(`| Column | Type | Nullable | Key | Default | Auto |`);
    out.push(`|---|---|---|---|---|---|`);
    for (const col of table.columns) {
      const badges = keyBadges(table, col.name).join(" ") || "—";
      const nullable = col.nullable ? "YES" : "NO";
      const def = col.defaultValue ? `\`${col.defaultValue}\`` : "—";
      const auto = col.autoIncrement ? "✓" : "—";
      out.push(
        `| \`${col.name.replace(/\|/g, "\\|")}\` | \`${col.type.replace(/\|/g, "\\|")}\` | ${nullable} | ${badges} | ${def} | ${auto} |`,
      );
    }
    out.push("");

    if (table.indexes.length > 0) {
      out.push(`**Indexes:**`);
      out.push("");
      for (const idx of table.indexes) {
        const kind = idx.primary ? "PRIMARY" : idx.unique ? "UNIQUE" : "INDEX";
        out.push(`- \`${kind}\` ${idx.name} on (${idx.columns.map((c) => `\`${c}\``).join(", ")})`);
      }
      out.push("");
    }
  }

  out.push("## Relationships");
  out.push("");
  if (schema.relationships.length === 0) {
    out.push("_No relationships defined._");
  } else {
    out.push(`| Source | Target | ON DELETE | ON UPDATE |`);
    out.push(`|---|---|---|---|`);
    for (const rel of schema.relationships) {
      out.push(
        `| \`${rel.sourceTable}.${rel.sourceColumn}\` → \`${rel.targetTable}.${rel.targetColumn}\` | ${rel.onDelete ?? "—"} | ${rel.onUpdate ?? "—"} |`,
      );
    }
  }
  out.push("");

  return out.join("\n");
}
